### ISSUE TITLE
Missing package dependency

### ISSUE THREAD

**Issue by smoke-indica** [syntax-tree/unist-util-select#8]
### Subject of the issue

Missing package dependency.

### Your environment

*   **OS**: Windows
*   **Packages**: 3.0.1
*   **Env**: node v12.14.0 , npm 6.13.4

### Steps to reproduce

https://github.com/syntax-tree/unist-util-select/blob/3100da1788143eff0272510aa38133be9b9f1a38/types/index.d.ts#L3

`import {Node} from 'unist'`

unist isn't included as a dependency in packages.json

Tried to use v3 in place of v2 in gatsby-remark-images-anywhere, got a warning about missing package dependencies.

### Expected behaviour

required package dependency stored in packages.json 

### Actual behaviour

Missing package dependency, fails to run

**Comment by ChristianMurphy** [comment]
We've avoided adding direct dependencies on `@types/` packages due to the issues outlined in https://github.com/unifiedjs/unified/issues/45 .
When using Typescript add the unist typings using `npm install @types/unist`.
