### ISSUE TITLE
Circular dependency any.js -> pseudo.js -> any.js using rollup

### ISSUE THREAD

**Issue by peterbabic** [syntax-tree/unist-util-select#9]
### Circular dependency any.js -> pseudo.js -> any.js using rollup

The rollup bundler is printing warnings about the detected circular dependency:

```
Circular dependency: node_modules/unist-util-select/lib/any.js -> node_modules/unist-util-select/lib/pseudo.js -> node_modules/unist-util-select/lib/any.js
Circular dependency: node_modules/unist-util-select/lib/any.js -> node_modules/unist-util-select/lib/pseudo.js -> /home/delmadord/work/sapper-blog/node_modules/unist-util-select/lib/any.js?commonjs-proxy -> node_modules/unist-util-select/lib/any.js
```

I will provide MVE to reproduce as soon as confirmed it is necessary. I may be mistaken of course, but from what I believe right now, any code analysis tool that would check for circular dependency issues should be able to spot this, not just rollup.

Lines that I believe lead to this behavior:

https://github.com/syntax-tree/unist-util-select/blob/2269b1c4fc8dc8c824d2757612c7c398ae0da80a/lib/any.js#L6

https://github.com/syntax-tree/unist-util-select/blob/2269b1c4fc8dc8c824d2757612c7c398ae0da80a/lib/pseudo.js#L8

Thank you for your work

**Comment by wooorm** [comment]
You're probably right! PR welcome to change it!

**Comment by peterbabic** [comment]
Would you agree with an approach to merge both files (pseudo.js and any.js) into one file, so they do not need to reference each other? This is the first thing that comes to my mind

**Comment by wooorm** [comment]
Hmm, they’re rather separate things.
A different approach which I think I like more: only `needsIndex` is used: https://github.com/syntax-tree/unist-util-select/blob/2269b1c4fc8dc8c824d2757612c7c398ae0da80a/lib/pseudo.js#L12. How about moving that to a new, third file?

**Comment by peterbabic** [comment]
Too bad
https://github.com/peterbabic/unist-util-select/commit/ea7f88fe0299fdb2da511e97dbc3eb0e6b40ec3e

Before:
![graph-before](https://user-images.githubusercontent.com/3952052/102118681-559b4400-3e40-11eb-9b29-d850081d2c3c.png)

After:
![graph-after](https://user-images.githubusercontent.com/3952052/102118761-6f3c8b80-3e40-11eb-9b47-00d3fdeea032.png)

Images generated with 
```
npx madge --image graph.png index.js
```

**Comment by wooorm** [comment]
oh interesting, and nice graph 😅
How about instead passing `any` in the [context objects here](https://github.com/syntax-tree/unist-util-select/blob/2269b1c4fc8dc8c824d2757612c7c398ae0da80a/index.js#L11) and using it in all places that used to require it?

**Comment by peterbabic** [comment]
Instructions unclear - `rg context` returned  no output

Please elaborate further :innocent:

**Comment by wooorm** [comment]
I meant that the third param is an object which is passed to most functions as the third param, so placing `any` in it means all functions can access it

**Comment by peterbabic** [comment]
Well, it works, tests passing

https://github.com/peterbabic/unist-util-select/commit/50ae64e2a50f5fb82ddcfb0bbf42e4aeb8acd357

![graph](https://user-images.githubusercontent.com/3952052/102128428-27bcfc00-3e4e-11eb-82aa-df9b633d7798.png)

**Comment by peterbabic** [comment]
Also, to reduce complexity further, I believe `needsIndex` moved into `needs.js` could be safely moved into `nest.js` or `test.js` looking at graphs

**EDIT:**
moved to `any.js` because it is the sole consumer of the array

https://github.com/peterbabic/unist-util-select/commit/2e09516e19acca71985c406224da72287d83ffc6

![graph](https://user-images.githubusercontent.com/3952052/102130661-60120980-3e51-11eb-9ca4-8d8b6b5ca09f.png)

**Comment by peterbabic** [comment]
I have made another branch with a single commit only applying the approach 2
https://github.com/peterbabic/unist-util-select/commit/375cdfe1672aaec2791e308c95f0a46942a6f158

The cyclic dependency is indeed resolved
![graph](https://user-images.githubusercontent.com/3952052/102207735-cab55a80-3ece-11eb-812a-54dccf12ccb1.png)

**Comment by andreavaccari** [comment]
Hi @wooorm. Thank you for the ecosystem you've built. I'm getting more warnings from `rollup`.

```
(!) Circular dependencies
node_modules/hast-util-to-html/lib/one.js -> node_modules/hast-util-to-html/lib/element.js -> node_modules/hast-util-to-html/lib/all.js -> node_modules/hast-util-to-html/lib/one.js
node_modules/hast-util-to-html/lib/one.js -> node_modules/hast-util-to-html/lib/element.js -> node_modules/hast-util-to-html/lib/all.js -> /Users/me/project/node_modules/hast-util-to-html/lib/one.js?commonjs-proxy -> node_modules/hast-util-to-html/lib/one.js
node_modules/mdast-util-to-hast/lib/one.js -> node_modules/mdast-util-to-hast/lib/all.js -> node_modules/mdast-util-to-hast/lib/one.js
node_modules/mdast-util-to-hast/lib/one.js -> node_modules/mdast-util-to-hast/lib/all.js -> /Users/me/project/node_modules/mdast-util-to-hast/lib/one.js?commonjs-proxy -> node_modules/mdast-util-to-hast/lib/one.js
```

I'm not familiar with the codebase yet and I don't think I'd be able to fix this easily.

Let me know if I should open new issues in `hast-util-to-html` and `mdast-util-to-hast`.

**Comment by peterbabic** [comment]
I am definitely for opening separate issues in both repositories and mentioning this one, as the solutions would most probably be quite different to each other. (disclaimer: I am not a maintainer/collaborator.)

**Comment by wooorm** [comment]
yup, I second @peterbabic’s suggestion!
